# Generated by Django 5.2 on 2026-02-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ManyToManyField(blank=True, help_text='Branches this user has access to', related_name='users', to='core.branch', verbose_name='branches'),
        ),
    ]
