# Generated by Django 5.2 on 2026-02-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
        ('users', '0005_customuser_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.ManyToManyField(blank=True, help_text='Branches this user has access to', related_name='branch_users', to='core.branch', verbose_name='branches'),
        ),
    ]
