# Generated by Django 5.2 on 2026-02-11 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the device', max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('device_type', models.CharField(choices=[('CASH_REGISTER', 'Cash Register'), ('PRICE_CHECKER', 'Price Checker'), ('STOCK_TERMINAL', 'Stock Terminal'), ('ADMIN_DEVICE', 'Admin Device'), ('OTHER', 'Other')], max_length=20, verbose_name='device type')),
                ('location', models.CharField(blank=True, help_text='Physical location of the device', max_length=200, null=True, verbose_name='location')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='serial number')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('mac_address', models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, null=True, verbose_name='MAC address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the device is active in the system', verbose_name='is active')),
                ('is_online', models.BooleanField(default=False, verbose_name='is online')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time the device checked in', null=True, verbose_name='last seen')),
                ('assigned_date', models.DateTimeField(blank=True, null=True, verbose_name='assigned date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to=settings.AUTH_USER_MODEL, verbose_name='assigned user')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key (e.g., "display_promotions", "timeout_seconds")', max_length=100, verbose_name='key')),
                ('value', models.CharField(help_text='Configuration value', max_length=500, verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='devices.device', verbose_name='device')),
            ],
            options={
                'verbose_name': 'device configuration',
                'verbose_name_plural': 'device configurations',
                'ordering': ['device', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type', 'is_active'], name='devices_dev_device__96d51f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['code'], name='devices_dev_code_767230_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceconfig',
            unique_together={('device', 'key')},
        ),
    ]
