# Generated by Django 5.2 on 2026-02-12 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
            ],
            options={
                'verbose_name': 'cash register',
                'verbose_name_plural': 'cash registers',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='PriceChecker',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('display_promotions', models.BooleanField(default=True, verbose_name='display promotions')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Idle timeout in seconds', verbose_name='timeout seconds')),
            ],
            options={
                'verbose_name': 'price checker',
                'verbose_name_plural': 'price checkers',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='StockTerminal',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('can_receive_shipments', models.BooleanField(default=True, verbose_name='can receive shipments')),
                ('require_photo', models.BooleanField(default=False, help_text='Require photo proof for stock adjustments', verbose_name='require photo')),
            ],
            options={
                'verbose_name': 'stock terminal',
                'verbose_name_plural': 'stock terminals',
            },
            bases=('devices.device',),
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_device__96d51f_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='device',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['polymorphic_ctype'], name='devices_dev_polymor_d33cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='devices_dev_is_acti_52b321_idx'),
        ),
    ]
