# Generated by Django 5.2 on 2026-02-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('devices', '0002_cashregister_pricechecker_stockterminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this device is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.branch', verbose_name='branch'),
        ),
    ]
