# Generated by Django 5.2 on 2026-02-18 23:47

import django.db.models.deletion
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
        ('devices', '0003_device_branch'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cashregister',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deviceconfig',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pricechecker',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stockterminal',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_configs', to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(help_text='Unique identifier for the device', max_length=50, verbose_name='code'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('company', 'code')},
        ),
    ]
