# Generated by Django 5.2 on 2026-02-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_cashregister_managers_alter_device_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cashregister',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='device',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pricechecker',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='stockterminal',
            managers=[
            ],
        ),
    ]
