# Generated by Django 5.2 on 2026-02-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255, verbose_name='name')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number (CUIT/RUT/etc.)', max_length=50, null=True, verbose_name='tax ID')),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='companies/logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name', max_length=255, verbose_name='name')),
                ('code', models.CharField(help_text='Unique code for identifying this branch', max_length=50, unique=True, verbose_name='code')),
                ('address', models.CharField(blank=True, help_text='Physical address of the branch', max_length=500, null=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(help_text='Company this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
