# Generated by Django 5.2 on 2026-02-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Unique code for identifying this branch', max_length=50, verbose_name='code'),
        ),
    ]
