# Generated by Django 5.2 on 2026-04-29 01:53

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Company address', max_length=500, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Company email', max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Legal name of the company', max_length=255, verbose_name='legal name'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Company phone number', max_length=50, verbose_name='phone'),
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(blank=True, default='IVA', help_text='Nombre del impuesto (ej: IVA)', max_length=50, verbose_name='tax name')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje de impuesto', max_digits=5, verbose_name='tax rate')),
                ('tax_enabled', models.BooleanField(default=True, help_text='Si el impuesto está activo', verbose_name='tax enabled')),
                ('currency_code', models.CharField(default='ARS', help_text='Código de moneda ISO (ej: ARS, USD)', max_length=3, verbose_name='currency code')),
                ('currency_symbol', models.CharField(default='$', help_text='Símbolo de moneda', max_length=5, verbose_name='currency symbol')),
                ('currency_decimals', models.PositiveSmallIntegerField(default=2, help_text='Cantidad de decimales', verbose_name='currency decimals')),
                ('receipt_header', models.TextField(blank=True, default='', help_text='Texto superior del ticket', verbose_name='receipt header')),
                ('receipt_footer', models.TextField(blank=True, default='', help_text='Texto inferior del ticket', verbose_name='receipt footer')),
                ('receipt_show_tax', models.BooleanField(default=True, help_text='Mostrar impuesto en el ticket', verbose_name='receipt show tax')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Permitir stock negativo', verbose_name='allow negative stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Umbral de stock bajo para alertas', verbose_name='low stock threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
