# Generated by Django 5.2 on 2025-07-01 23:05

import django.core.validators
import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('phone', utils.fields.PhoneNumberField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Máximo 20 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('cuit', models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d{1}$', 'Ingrese un CUIT válido.')], verbose_name='cuit')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal code')),
                ('billing_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('M', 'M'), ('T', 'T')], default='C', max_length=1, verbose_name='billing type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_customer_account', models.BooleanField(default=False, verbose_name='approved customer account')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'indexes': [models.Index(fields=['dni'], name='dni_index'), models.Index(fields=['cuit'], name='cuit_index'), models.Index(fields=['approved_customer_account'], name='approved_cc_index'), models.Index(fields=['name'], name='name_index'), models.Index(fields=['last_name'], name='last_name_index'), models.Index(fields=['phone'], name='phone_index'), models.Index(fields=['email'], name='email_index')],
            },
        ),
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='opening date')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='credit limit')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_accounts', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'current account',
                'verbose_name_plural': 'current accounts',
            },
        ),
        migrations.CreateModel(
            name='CustomerBalanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('movement_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('ADJUSTMENT', 'Adjustment'), ('REFUND', 'Refund'), ('REVERSAL', 'Reversal')], max_length=20, verbose_name='movement type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reconciled', models.BooleanField(default=False, verbose_name='reconciled')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='reconciled at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_records', to='clients.currentaccount', verbose_name='current account')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_by', to=settings.AUTH_USER_MODEL)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_records', to='clients.customerbalancerecord', verbose_name='related to')),
            ],
            options={
                'verbose_name': 'customer balance record',
                'verbose_name_plural': 'customer balance records',
                'ordering': ['-created_at'],
            },
        ),
    ]
