# Generated by Django 5.1.6 on 2025-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerbalancerecord',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
