# Generated by Django 5.2 on 2025-08-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbalancerecord',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_balance_records', to='sales.sale', verbose_name='sale'),
        ),
        migrations.AddIndex(
            model_name='customerbalancerecord',
            index=models.Index(fields=['customer_account'], name='customer_account_index'),
        ),
        migrations.AddIndex(
            model_name='customerbalancerecord',
            index=models.Index(fields=['created_at'], name='created_at_index'),
        ),
        migrations.AddIndex(
            model_name='customerbalancerecord',
            index=models.Index(fields=['movement_type'], name='movement_type_index'),
        ),
        migrations.AddConstraint(
            model_name='customerbalancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'REVERSAL')), fields=('related_to', 'movement_type'), name='unique_reversal_per_record'),
        ),
    ]
