# Generated by Django 5.2 on 2025-07-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customerbalancerecord',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_balance_records', to='sales.sale', verbose_name='sale'),
        ),
    ]
