# Generated by Django 5.1.6 on 2025-03-26 14:48

import django.core.validators
import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='customerbalancerecord',
            options={'verbose_name': 'customer balance record', 'verbose_name_plural': 'customer balance records'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='approved_customer_account',
            field=models.BooleanField(default=False, verbose_name='approved customer account'),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('E', 'E'), ('M', 'M'), ('T', 'T')], default='C', max_length=1, verbose_name='billing type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d{1}$', 'Ingrese un CUIT válido.')], verbose_name='cuit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=utils.fields.PhoneNumberField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+999999999'. Máximo 20 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customerbalancerecord',
            name='amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='customerbalancerecord',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='customerbalancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
