# Generated by Django 5.2 on 2025-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='approved_customer_account',
            field=models.BooleanField(default=True, verbose_name='approved customer account'),
        ),
    ]
