# Generated by Django 5.1.6 on 2025-04-17 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d{1}$', 'Ingrese un CUIT válido.')], verbose_name='cuit'),
        ),
    ]
