# Generated by Django 5.2 on 2026-02-18 23:47

import django.core.validators
import django.db.models.deletion
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_email_alter_client_is_deleted'),
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customeraccount',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='customerbalancerecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_balance_records', to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d{1}$', 'Ingrese un CUIT válido.')], verbose_name='cuit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'cuit'), ('company', 'email')},
        ),
    ]
