# Generated by Django 5.2 on 2025-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_city_remove_client_country'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['dni'], name='dni_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['cuit'], name='cuit_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['approved_customer_account'], name='approved_cc_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['balance'], name='balance_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='name_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name'], name='last_name_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='phone_index'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='email_index'),
        ),
    ]
