# Generated by Django 5.2 on 2026-02-21 23:21

import clients.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_managers_alter_customeraccount_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customerbalancerecord',
            managers=[
                ('objects', clients.managers.BalanceRecordsManager()),
            ],
        ),
    ]
