FROM python:3.13-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Solo lo necesario para SQLite y pruebas
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libsqlite3-dev && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
RUN pip install --upgrade pip && pip install .

COPY . .

ENV DJANGO_SETTINGS_MODULE=BagualesPOS.settings.testing

CMD ["python", "manage.py", "test"]
