# Generated by Django 5.2 on 2026-03-04 21:08

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
        ('inventory', '0005_inventory_branch_alter_inventory_product_and_more'),
        ('products', '0013_alter_color_managers_alter_gender_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('REDUCTION', 'Stock Reduction'), ('ADDITION', 'Stock Addition'), ('CORRECTION', 'Stock Correction')], default='REDUCTION', max_length=20, verbose_name='adjustment type')),
                ('quantity', models.IntegerField(help_text='Quantity to adjust (positive or negative)', verbose_name='quantity')),
                ('reason', models.TextField(help_text='Reason for the adjustment', verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('rejection_note', models.TextField(blank=True, null=True, verbose_name='rejection note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_requests', to='core.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_requests', to='core.company', verbose_name='company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_requests', to='products.product', verbose_name='product')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments_requested', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
            ],
            options={
                'verbose_name': 'stock adjustment request',
                'verbose_name_plural': 'stock adjustment requests',
                'ordering': ['-created_at'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('SALE', 'Sale'), ('ADJUSTMENT', 'Manual Adjustment'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('CORRECTION', 'Correction')], max_length=20, verbose_name='movement type')),
                ('previous_quantity', models.IntegerField(verbose_name='previous quantity')),
                ('new_quantity', models.IntegerField(verbose_name='new quantity')),
                ('quantity_change', models.IntegerField(verbose_name='quantity change')),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of related record (sale, adjustment, etc.)', null=True, verbose_name='reference ID')),
                ('reference_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='reference model')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.company', verbose_name='company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
