# Generated by Django 5.2 on 2026-02-11 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'cash register',
                'verbose_name_plural': 'cash registers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SUSPENDED', 'Suspended')], default='OPEN', max_length=20, verbose_name='status')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='opening date')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='closing date')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='opening balance')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='closing balance')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cash.cashregister', verbose_name='cash register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'cash session',
                'verbose_name_plural': 'cash sessions',
                'ordering': ['-opening_date'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('CLOSING', 'Closing Balance'), ('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out')], max_length=20, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cash.cashsession', verbose_name='cash session')),
            ],
            options={
                'verbose_name': 'cash movement',
                'verbose_name_plural': 'cash movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
