# Generated by Django 5.2 on 2026-02-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('devices', '0002_cashregister_pricechecker_stockterminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashsession',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='devices.cashregister', verbose_name='cash register'),
        ),
        migrations.DeleteModel(
            name='CashRegister',
        ),
    ]
