# Generated by Django 5.2 on 2026-02-18 23:47

import django.db.models.deletion
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cashsession_cash_register_delete_cashregister'),
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cashmovement',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cashsession',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='core.company', verbose_name='company'),
        ),
    ]
