# Generated by Django 5.2 on 2026-04-29 01:53

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_company_address_company_email_company_legal_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SALE_CREATED', 'Sale Created'), ('SALE_CANCELED', 'Sale Canceled'), ('ADJUSTMENT_CREATED', 'Adjustment Created'), ('ADJUSTMENT_APPROVED', 'Adjustment Approved'), ('ADJUSTMENT_REJECTED', 'Adjustment Rejected'), ('RETURN_PROCESSED', 'Return Processed'), ('RETURN_CANCELED', 'Return Canceled'), ('TRANSFER_CREATED', 'Transfer Created'), ('TRANSFER_APPROVED', 'Transfer Approved'), ('TRANSFER_COMPLETED', 'Transfer Completed'), ('PRICE_CHANGED', 'Price Changed'), ('PRICE_BULK_UPDATE', 'Bulk Price Update'), ('CASH_SESSION_OPENED', 'Cash Session Opened'), ('CASH_SESSION_CLOSED', 'Cash Session Closed'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('SETTINGS_UPDATED', 'Settings Updated')], max_length=30, verbose_name='action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to='core.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='core.company', verbose_name='company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit record',
                'verbose_name_plural': 'audit records',
                'ordering': ['-created_at'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
