# Generated by Django 5.2 on 2026-02-11 21:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='account_record_id',
            field=models.IntegerField(blank=True, help_text='Reference to CustomerBalanceRecord if applicable', null=True, verbose_name='account record ID'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='payment status'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sale price'),
        ),
    ]
