# Generated by Django 5.1.6 on 2025-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale_price',
            field=models.IntegerField(),
        ),
    ]
