# Generated by Django 5.2 on 2026-02-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('sales', '0002_sale_account_record_id_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='cash.cashsession', verbose_name='cash session'),
        ),
    ]
