# Generated by Django 5.1.6 on 2025-03-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_and_more'),
        ('products', '0003_alter_brand_options_alter_category_options_and_more'),
        ('sales', '0002_alter_sale_total_amount_alter_saledetail_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymethod',
            options={'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'sale detail', 'verbose_name_plural': 'sale details'},
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='canceled'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pay_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.paymethod', verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Cantidad', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale_price',
            field=models.IntegerField(verbose_name='sale price'),
        ),
    ]
