# Generated by Django 5.1.6 on 2025-05-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_city_remove_client_country'),
        ('sales', '0003_alter_paymethod_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='client'),
        ),
    ]
