# Generated by Django 5.2 on 2026-02-14 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_email_alter_client_is_deleted'),
        ('sales', '0003_sale_cash_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'sale detail', 'verbose_name_plural': 'sale details'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='account_record_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='account_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.customerbalancerecord', verbose_name='account record'),
        ),
    ]
