# Generated by Django 5.2 on 2026-02-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_code'),
        ('sales', '0004_alter_sale_options_alter_saledetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this sale was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.branch', verbose_name='branch'),
        ),
    ]
