# Generated by Django 5.2 on 2026-02-18 23:47

import django.db.models.deletion
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
        ('sales', '0005_sale_branch'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paymethod',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='saledetail',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='paymethod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='core.company', verbose_name='company'),
        ),
        migrations.AlterUniqueTogether(
            name='paymethod',
            unique_together={('company', 'name')},
        ),
    ]
