# Generated by Django 5.2 on 2026-02-21 23:21

import sales.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_paymethod_managers_alter_saledetail_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sale',
            managers=[
                ('objects', sales.managers.SalesManager()),
            ],
        ),
    ]
