# Generated by Django 5.2 on 2026-04-29 01:53

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_alter_cashmovement_managers_and_more'),
        ('clients', '0007_alter_customerbalancerecord_managers'),
        ('core', '0004_company_address_company_email_company_legal_name_and_more'),
        ('products', '0014_pricehistory'),
        ('sales', '0007_alter_sale_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='COMPLETED', max_length=20, verbose_name='status')),
                ('reason_type', models.CharField(choices=[('DEFECTIVE', 'Defective / Damaged'), ('WRONG_ITEM', 'Wrong Item'), ('NOT_NEEDED', 'Not Needed'), ('OTHER', 'Other')], max_length=20, verbose_name='reason type')),
                ('reason_notes', models.TextField(blank=True, default='', verbose_name='reason notes')),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total refund amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_authorized', to=settings.AUTH_USER_MODEL, verbose_name='authorized by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.branch', verbose_name='branch')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='cash.cashsession', verbose_name='cash session')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.company', verbose_name='company')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'return',
                'verbose_name_plural': 'returns',
                'ordering': ['-created_at'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='unit price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('condition', models.CharField(choices=[('RESALEABLE', 'Resaleable'), ('DAMAGED', 'Damaged')], default='RESALEABLE', max_length=20, verbose_name='condition')),
                ('restock', models.BooleanField(default=True, verbose_name='restock')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='core.company', verbose_name='company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.return', verbose_name='return')),
                ('sale_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saledetail', verbose_name='sale detail')),
            ],
            options={
                'verbose_name': 'return detail',
                'verbose_name_plural': 'return details',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_method', models.CharField(choices=[('CASH', 'Cash'), ('STORE_CREDIT', 'Store Credit'), ('ORIGINAL_METHOD', 'Original Payment Method')], max_length=20, verbose_name='refund method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('account_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.customerbalancerecord', verbose_name='account record')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_refunds', to='core.company', verbose_name='company')),
                ('pay_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.paymethod', verbose_name='pay method')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.return', verbose_name='return')),
            ],
            options={
                'verbose_name': 'return refund',
                'verbose_name_plural': 'return refunds',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
