# Generated by Django 5.1.6 on 2025-04-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='numeric_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='numeric size'),
        ),
    ]
