# Generated by Django 5.1.6 on 2025-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_deleted_at_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=7, verbose_name='code'),
        ),
    ]
