# Generated by Django 5.2 on 2025-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettersize',
            name='short_name',
            field=models.CharField(default='Algo', max_length=4, verbose_name='short name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lettersize',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
