# Generated by Django 5.2 on 2026-02-21 23:21

import django.db.models.deletion
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_managers_alter_company_managers_and_more'),
        ('products', '0012_alter_brand_managers_alter_category_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='color',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='gender',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lettersize',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materials',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='season',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subcategory',
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='gender',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='lettersize',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_sizes', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='materials',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='season',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='core.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lettersize',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lettersize',
            name='short_name',
            field=models.CharField(max_length=4, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='gender',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lettersize',
            unique_together={('company', 'name'), ('company', 'short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='materials',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('company', 'name')},
        ),
    ]
