# Generated by Django 5.2 on 2026-04-29 01:53

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_address_company_email_company_legal_name_and_more'),
        ('products', '0013_alter_color_managers_alter_gender_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('sale_price', 'Sale Price'), ('cost_price', 'Cost Price')], max_length=20, verbose_name='field')),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='old value')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='new value')),
                ('change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='change percentage')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='reason')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('BULK_UPDATE', 'Bulk Update')], default='MANUAL', max_length=20, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='core.company', verbose_name='company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'price history',
                'verbose_name_plural': 'price histories',
                'ordering': ['-created_at'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
